debug: false
inference_root: /disk/vanishing_data/ju878/log_finn
normalize: true
num_frames: -1
num_last_n_list:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
range_image:
  fov_down: -25.0
  fov_up: 3.0
  height: 64
  max_range: 50.0
  min_range: 2.0
  width: 2048
scan_folder: /disk/vanishing_data/ju878/CODA_for_detection_method/sequences
scan_root: /disk/vanishing_data/ju878/CODA_for_detection_method/sequences
sequences:
- 1
- 2
- 3
- 4
- 5
- 1058
- 1059
- 1060
- 1061
- 1062
- 1366
- 1367
- 1371
- 1372
- 1373
split: valid
visualize: true
